version: "3.8"

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - 3000:80
  nginx: 
        restart: unless-stopped
        build:
            context: .
        ports:
            - 80:80